### ISSUE TITLE
Link to the Windows 8 sample is broken

### ISSUE THREAD

**Issue by codec-abc** [ljubobratovicrelja/camera_calibration#1]
The [link in the Readme](https://www.dropbox.com/s/tot12zm0qi2rsl1/camera_calibration_vc12_x64.zip?dl=0) is broken (404) and thus I am not able to download the compiled sample for Windows 8. Would you mind re-uploading if you still have it? Moreover, you may want to use Github release for that.

**Comment by ljubobratovicrelja** [comment]
Fixed in 62480f97a435f51ee830d12829fea4fe5df0aca2
